source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

target "SKTagView" do
pod 'Masonry', '~> 0.6.3'
pod 'HexColors', '~> 3.0'
pod 'YYText', '~> 1.0.7'
end

target "SKTagViewTests" do
end

