use_frameworks!

target 'TTGTagCollectionView_Example' do
  pod 'YYText', '~> 1.0.7'
  pod 'TTGTagCollectionView', :path => '../'

  target 'TTGTagCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
